version: '3.9'

services:
  license:
    image: casazium/license:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_FILE=./data/license.db
    restart: unless-stopped
